### ISSUE TITLE
Skill fails when no Dockerfile is present

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/docker-build-skill#16]
configuration is "all repos" and everything else default

```
name: docker-build-skill
version: 1.1.3-38
upgrade_policy: latest_compatible_release
namespace: atomist
configurations:
- name: Docker Build
  enabled: true
  parameters:
  - name: repos
    value: {}
  resourceProviders:
  - name: docker_push_registry
    selectedResourceProviders:
    - id: AEIB5886C_c534d873-3053-4e66-85d0-4d3697ad60cc
```

On repos, that do not contain a `Dockerfile`, the skill fails and the mapped channel gets a message:

<img width="830" alt="Screenshot 2020-05-15 17 36 02" src="https://user-images.githubusercontent.com/1643888/82105887-92e4fb00-96d2-11ea-8fc5-29bebdd59be7.png">

Example repo is:  https://github.com/slimslender/nextjs-blog

I expect the skill to run for this but I think it should not fail.
